### ISSUE TITLE
The imgflo.org domain has been taken

### ISSUE THREAD

**Issue by cam1170** [imgflo/imgflo#104]
I just found this project and I don't know the story, but it looks like the website isn't for this project anymore. It should probably be either bought back or removed from this repo.

**Comment by jonnor** [comment]
Hi @cam1170 - thank you for reporting this. Indeed I stopped paying for imgflo . org domain a while back, as this project is dormant for several years. I have now removed the links to that from the Github repo page, which I believe is the only place that linked it.

**Comment by jonnor** [comment]
Have also fixed package.json files now. Think that should be all. Thanks again!
