### ISSUE TITLE
Allow to pick images directly from web service

### ISSUE THREAD

**Issue by jonnor** [imgflo/imgflo#28]
In the general case (imgflo not running on same machine as UI),  it would be nice to have image pickers that allows getting images by HTTP, or directly from Google image search, Picasa, Facebook gallery, Flicker, Creative Commons search.

This should probably be built with NoFlo, as there are also many non-imgflo uses for such widgets.

**Comment by forresto** [comment]
https://www.filepicker.io/ is a decent service / would upload from all of those to our S3. $9/mo. I use it in http://app.meemoo.org/ "images" tab.

**Comment by jonnor** [comment]
Out of scope
